### ISSUE TITLE
wrong position of resizer icon in jQuery UI dialog

### ISSUE THREAD

**Issue by OlegKi** [mkkeck/jquery-ui-icons#1]
It's interesting project! It's the initial version, so it's clear that it could be some bugs and problems.

For example, the resizer icon (`ui-icon-gripsmall-diagonal-se`) in the Dialog (see your demo) have some problems:
- `position: relative` instead of `position: absolute` will be used which make the wrong place of the icon.
- jQuery UI set additional `ui-resizable-se` class on the resizer div. Because of that the `width`, `height`, `right` and `bottom` from the CSS rule [.ui-dialog .ui-resizable-se](https://github.com/jquery/jquery-ui/blob/1.11.4/themes/base/dialog.css#L61-L67) will be applied which makes the icon not visible.

**Comment by mkkeck** [comment]
Should be fixed now.
Thanks for your suggestions.
