### ISSUE TITLE
Datepicker Shows Prev/Next Text

### ISSUE THREAD

**Issue by CyrixInstead** [mkkeck/jquery-ui-icons#2]
The text-indent value of the .ui-icon element (line 21) in the jquery-ui.icons.css file is set to zero. This shows the text where only the icon should show, for example the datepicker shows the words 'Prev' and 'Next' in your demo. Setting a value of text-indent: -99999px; hides the text leaving only the icon correctly showing.

**Comment by nacho4d** [comment]
I am having the same issue. I tried `text-indent: -99999px;` but things got worse. Now most icons are overlapped by its icons :(
I am not an expert in css/js so I have no clue why this happens.
I hope there is a fix for this, this library looks really really promising! :+1:

**Comment by CyrixInstead** [comment]
Did you change the text-indent of the .ui-icon element on line 21 in the icons stylesheet? The style already exists there with a value of zero, just change it to -99999px. I've highlighted it below.

![image](https://cloud.githubusercontent.com/assets/1932141/8547119/ae619c7a-24b4-11e5-9063-1995cbe69659.png)

**Comment by nacho4d** [comment]
Now I see!. In Chrome 43 and Safari 8 it works. However in Firefox 39 (the browser I was trying) it looks broken in 3 places:
- Icon buttons.
- DatePicker "Prev" and "Next" buttons.
- Select Menu right icon position

<img width="199" alt="screen shot 2015-07-08 at 10 15 32" src="https://cloud.githubusercontent.com/assets/111651/8561058/759ab222-255a-11e5-9135-78b04da7ee38.png">

## Workaround

Just add `text-indent: -28.5px;` to  `.ui-datepicker .ui-datepicker-prev .ui-icon, .ui-datepicker .ui-datepicker-next .ui-icon` rule in jquery-ui.icons.css. This hardcoded change won't affect other than date pickers so as a work-around is ok I guess.

<img width="404" alt="screen shot 2015-07-08 at 10 41 04" src="https://cloud.githubusercontent.com/assets/111651/8561279/04a3df22-255e-11e5-9f07-821a85d72cca.png">

**Comment by CyrixInstead** [comment]
The only browser I hadn't tried it in yet was Firefox and I can confirm it doesn't work in FF 38 either. Thanks for the update.

\Edit - the problem now is that although it renders the same way across all of the browsers, you can still see the prev/next text behind the icon. This is a deal breaker for me and is beyond my abilities to fix at the moment, although I will keep trying.

@mkkeck any ideas here sir?

**Comment by CyrixInstead** [comment]
I happened to have an older version of the plugin from a few weeks ago and the datepicker does work in Firefox in that version and from that I have come up with a solution that works in Chrome, FF and IE. I've not tested Safari.

## Latest workaround

In jquery-ui.icons.css change the .`ui-icon` rule to have `height: 1em; width: 1em;`
and `text-indent: -99999px;`. Change the `.ui-datepicker .ui-datepicker-prev .ui-icon, .ui-datepicker .ui-datepicker-next .ui-icon` rule to not use `overflow: hidden;` so that the bottom of the icons is not cut off.

**Comment by mkkeck** [comment]
Should be fixed with latest commit

**Comment by nacho4d** [comment]
Now looks even nicer! Thanks!
