### ISSUE TITLE
Left edge of icons slightly cut off

### ISSUE THREAD

**Issue by CyrixInstead** [mkkeck/jquery-ui-icons#3]
The left edge of the icons appears to be cut off slightly, this is particularly noticeable on the circular icons and affects the demo page. It can be seen on the button icons and on the datepicker prev/next icons (when hiding the text with text-indent, see bug #2 I logged).

As a quick fix I added padding-left: 1px; to the .ui-icon element (line 21) in the jquery-ui.icons.css file. Although this fixes the problem and you can clearly see the full icon, it does make everything a bit bigger and I doubt it's a proper fix, so thought I'd best log a bug for the issue.

**Comment by mkkeck** [comment]
Should be fixed with latest commit
