### ISSUE TITLE
publishing results in well-known repositories

### ISSUE THREAD

**Issue by OlegKi** [mkkeck/jquery-ui-icons#4]
I recommend you to publish your results in well-known repositories: [npmjs](https://www.npmjs.com/), [bower](http://bower.io/), [nuget](https://www.nuget.org/). You can post it additionally to two free CDNs: [cdnjs](https://cdnjs.com/) and  [jsDelivr](http://www.jsdelivr.com/). All this is for free, but it can help to make results of your work more known by other people. By the way it you do the work once then creating new tag in GitHub will automatically publish new versions on many from the sources which I mention. I did the work with one my product and can explain you required steps if you would have some problem in understanding how to publish in some from described above repositories of CDNs. You can start with bower and npmjs where you need just create JSON file which is almost the same what you have already and start some command line tools. See [here](https://docs.npmjs.com/getting-started/publishing-npm-packages), [here](http://blog.npmjs.org/post/112712169830/making-your-jquery-plugin-work-better-with-npm) and [here](http://bower.io/docs/creating-packages/). You can easy to find more information in internet.

**Comment by mkkeck** [comment]
Hi, thats sounds great.
But at the moment, I think, I'm not really ready with my work. Some things, which I would include near future, are missing. Perhabs with the next major release, I would do, if it does not make to much work for me too.

**Comment by OlegKi** [comment]
It looks complex at the beginning. but it's really simple at the end. You have already `ui-iconfont.jquery.json` file. Why? Probably renaming it to `package.json` and executing of `npm publish` will publish the version in npm repository. Starting `bower init` helps to create `bower.json` (see [here](http://bower.io/docs/creating-packages/)). You can look at [the repository](https://github.com/free-jqgrid/jqGrid) for examples of JSON files and look at [the article](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs) which shows how to use the same results from CDNs. All sounds complex till you did it. After that all seems easy.

The problem is where you what to share your results with other or not. You post your results to GitHub, but not so many people knows about it. Publishing current results (even beta results) in well-known repositories is nothing more as creating reference to your Git repository. You should decide yourself whether you need it or not.

**Comment by mkkeck** [comment]
"It looks complex at the beginning. but it's really simple at the end. You have already ui-iconfont.jquery.json file. Why?"
For jQuery's Plugin Page?

**Comment by OlegKi** [comment]
If you go to [The jQuery Plugin Registry](http://plugins.jquery.com/) you will read: "The jQuery Plugin Registry is in read-only mode. New plugin releases will not be processed. We recommend moving to npm, using "jquery-plugin" as the keyword in your [package.json](https://www.npmjs.org/browse/keyword/jquery-plugin). The npm blog has [instructions for publishing your plugin to npm](http://blog.npmjs.org/post/111475741445/publishing-your-jquery-plugin-to-npm-the-quick)." It's the same what I suggested you. The state with the jQuery Plugin Registry exists since about a year already. It's practically closed. Publishing in npmjs and bower repository are the preferred way now. It makes the results of your work more accessible by other people.

**Comment by mkkeck** [comment]
Package.json for NPMjs is now available.
Bower and perhabs others will follow in future.
