### ISSUE TITLE
Trash icon looks like a beer glass

### ISSUE THREAD

**Issue by CyrixInstead** [mkkeck/jquery-ui-icons#7]
Hi, your work is excellent and in the interest of making it even better for I was wondering whether you would be able to add/replace a better (IMHO) icon for the trash can? The old JQUI icon was a trash can similar to the one used in Font Awesome (http://fortawesome.github.io/Font-Awesome/icon/trash-o/) but the new icon looks like a beer glass. Every colleague I have spoken to agrees that it looks like a beer glass, and I've had to change our use of that icon for the cross icon as it didn't look goo in our shopping cart. We use a delete icon next to each item in the cart, and it looked like a stack of beer glasses :-)

I would imagine we're not alone in thinking this, so I thought perhaps it might be a worthwhile endeavour for the good of the plugin. What are your thoughts?

**Comment by mkkeck** [comment]
Of course, it may be look like a beer glass. At drawing this, I was looking at my recycle bin under my desktop. I am drawing some new icons for next update. There would be a new trash icon, which replaces the beer glass.

**Comment by CyrixInstead** [comment]
Excellent, thank you very much and thank you for not taking offence to my suggestion :)

**Comment by mkkeck** [comment]
New icons for trash-can are merged now in new version 2.x.
- ui-icon-trash
- ui-icon-trash-b
