### ISSUE TITLE
I'm missing T for TEXT as an icon!

### ISSUE THREAD

**Issue by FlemmingH** [mkkeck/jquery-ui-icons#9]
Just like the "i" for info it could be nice with some icons typically used for text-formating. But right now i'm missing the "T" as symbol for the button [create new text] in a editor. So i'm forced to try making a font fitting the icons boundary which is giving me some troubles.

**Comment by mkkeck** [comment]
At the moment, I would not add new icons for text-formating, escpacially an icon with T for "new text". Icons for text formating are often shipped with your used online (WYSIWYG) editor (e.g. TinyMCE, CK-editor, ...). As an alternative for your "T"-symbol, you can use one of these icons: 'file', 'file-text', 'input' / 'rename'
